# Generated by Django 5.1 on 2024-09-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0002_alter_log_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
