# Generated by Django 5.1 on 2024-09-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0004_remove_profile_bio_profile_dob_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
