# Generated by Django 5.1 on 2024-09-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0006_shift_leave_payroll_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('Trưởng Phòng', 'Trưởng Phòng'), ('Tổ Trưởng', 'Tổ Trưởng'), ('Nhân Viên', 'Nhân Viên')], default='Nhân Viên', max_length=25),
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
