# Generated by Django 5.1 on 2024-09-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0008_alter_attendance_salary_alter_attendance_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
