# Generated by Django 5.1 on 2024-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_id', '0009_attendance_checked_in_attendance_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checked_in',
            field=models.BooleanField(default=True),
        ),
    ]
